### PR TITLE
Added the ability to create an Eclipse project.

### PR DESCRIPTION
**Pull request by nedtwigg**

### CODE REVIEW

**Comment by hrldcpr** [comment]
thanks @nedtwigg!

can you tell me a bit about what this change accomplishes, and whether it will interfere with people who aren't using Eclipse?

**Comment by nedtwigg** [comment]
If you run `gradlew eclipse`, it will create an Eclipse project.  It doesn't affect anything else (`gradlew build` is unchanged).  It also updates .gitignore to ignore all of the eclipse-specific metadata.

**Comment by blackdrag** [comment]
@hrldcpr what IDE do you use?

**Comment by hrldcpr** [comment]
Whoops sorry this never got addressed 😬

**Comment by nedtwigg** [comment]
No problem!  Love the library, love the recent updates.  I don't think this PR mattered hardly at all, just wanted to take the distraction off your plate :)

**Pull request closed without merging**
