### PR TITLE
Fixes #16 - HashPMap now implements java.io.Serializable

### LINKED ISSUE #16: HashPMap does not implement Serializable
_From [thorstenvogel@gmail.com](https://code.google.com/u/thorstenvogel@gmail.com/) on 2011-05-26T10:15:10Z_

HashPMap does not implement Serializable. This is not really compatible with java.util.HashMap. Are you planning to support serialization in the future?

_Original issue: http://code.google.com/p/pcollections/issues/detail?id=16_

### PR DESCRIPTION
**Pull request by matei-dragu**

### CODE REVIEW

**Comment by hrldcpr** [comment]
Thanks, this is great, there's even tests!

I think we should be consistent and make all of the data structures Serializable; only doing it partially seems potentially confusing. (If you don't have time I will get to eventually, this is already a useful start.)

We should also declare `private static final long serialVersionUID = 1L` in every Serializable class, it is strongly encouraged in the Serializable documentation.

**Comment by matei-dragu** [comment]
Fair points - how about now?

**Comment by hrldcpr** [comment]
That was fast, looks great 🚀

**Comment by hrldcpr** [comment]
I'll do a release with these changes this weekend.

**Comment by matei-dragu** [comment]
Great, sounds good!

**Pull request merged**
