### PR TITLE
Throw UnsupportedOperationException from HashPMap, IntTreePMap, and OrderedPSet

### PR DESCRIPTION
**Pull request by prdoyle**
Selfishly implement the parts of #93 that affect me personally. Because these structures don't obey the contract of `Map` and `Set`, I can't use them as drop-in replacements without failing my own unit tests.

Three lines of real changes; 90 more lines around unit testing.

(Also adds seeds to the randomized unit tests to make them reproducible.)

### CODE REVIEW

**Comment by hrldcpr** [comment]
Awesome, thanks! Looks good, and the tests run for me. This makes progress towards #93

**Comment by hrldcpr** [comment]
Technically this is a breaking change, since previously something like `OrderedPSet.empty().clear()` wouldn't fail. So I'll make sure to increment the major version before releasing this, and also I'll finish up #93 while I'm at it so I don't have to increment the major version yet again after that.

**Comment by prdoyle** [comment]
Ah true, good catch!

Maybe I can pitch in on the weekend with some more of #93.

**Comment by hrldcpr** [comment]
I threw it together earlier, but thanks! (And don't worry, it was pretty easy)

**Pull request merged**
